set nocompatible              " be iMproved
filetype off                  " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required!
Bundle 'gmarik/vundle'

" My bundles here:
"
" original repos on GitHub

" Bundle 'Lokaltog/vim-easymotion'

" Status line and buffer explorer
Bundle 'bling/vim-airline'

" Fugitive is a Git plugin
Bundle 'tpope/vim-fugitive'

Bundle 'airblade/vim-gitgutter'

Bundle 'scrooloose/nerdtree'

Bundle 'terryma/vim-multiple-cursors'

" Lint, codecompletion, documentation lookup, jump to classes, refactoring
" tools, etc...
Bundle 'klen/python-mode'

" Full path fuzzy file, buffer, mru, tag, ... finder for Vim.
Bundle 'kien/ctrlp.vim'

Bundle 'majutsushi/tagbar'

" NERDCommenter allows you to wrangle your code comments, regardless of
" filetype.
Bundle 'ddollar/nerdcommenter'

" Bundle 'rstacruz/sparkup', {'rtp': 'vim/'}
" Bundle 'tpope/vim-rails.git'
" vim-scripts repos
" Bundle 'L9'
" Bundle 'FuzzyFinder'
" non-GitHub repos
" Bundle 'git://git.wincent.com/command-t.git'
" Git repos on your local machine (i.e. when working on your own plugin)
" Bundle 'file:///Users/gmarik/path/to/plugin'
" ...

filetype plugin indent on     " required!
"
" Brief help
" :BundleList          - list configured bundles
" :BundleInstall(!)    - install (update) bundles
" :BundleSearch(!) foo - search (or refresh cache first) for foo
" :BundleClean(!)      - confirm (or auto-approve) removal of unused bundles
"
" see :h vundle for more details or wiki for FAQ
" NOTE: comments after Bundle commands are not allowed.


set showcmd   " Show incomplete cmds down the bottom
set incsearch " Find the next match as we type the search
set hlsearch  " Hilight searches by default
set magic " Set magic on, for regular expressions
set wildmode=longest,full " Complete longest common string, then each full match
set wildmenu
set ignorecase
set smartcase
set history=1000
set ff=unix
set encoding=utf-8
set fileencoding=utf-8
set autoread
set backspace=indent,eol,start
set hidden	" Switch buffers even if the current one have unsaved changes
syntax on


" Remove trailing whitespace
autocmd BufWritePre * :%s/\s\+$//e


" Map Ctrl+<movement> to move around windows.
map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-l> <c-w>l
map <c-h> <c-w>h

" Map <leader>+<movement> to move around buffers
nnoremap <Leader><Left> :bp<CR>
nnoremap <Leader>h :bp<CR>
nnoremap <Leader><Right> :bn<CR>
nnoremap <Leader>l :bn<CR>

nnoremap <Leader>w :bd<CR>


" Powerline setup
set term=xterm-256color
set guifont=Menlo\ for\ Powerline\ 9
set laststatus=2

" NERD Tree setup
" F2 to toggle the tree view
map <F2> :NERDTreeToggle<CR>
let NERDTreeIgnore=['\~$', '\.pyc$']

" Python mode setup
let g:pymode_lint_ignore = "E501"
let g:pymode_lint_select = ""
let g:pymode_folding = 0

set wildignore+=*.o,*.pyc

" Tagbar setup
map <silent> <F3> :TagbarToggle<CR>
let tagbar_left = 1
let tagbar_autoclose = 1
let tagbar_autofocus = 1
let tagbar_sort = 0

" Pymode
let pymode_doc = 0

" vim-airline
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme= "powerlineish"

" git gutter
highlight clear SignColumn
