set nocompatible              " be iMproved
filetype off                  " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required!
Bundle 'gmarik/vundle'

" My bundles here:
"
" original repos on GitHub

Bundle 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}
" Bundle 'Lokaltog/vim-easymotion'

" Fugitive is a Git plugin
Bundle 'tpope/vim-fugitive'

Bundle 'scrooloose/nerdtree'

" Lint, codecompletion, documentation lookup, jump to classes, refactoring
" tools, etc...
Bundle 'klen/python-mode'

" buffer explorer
Bundle 'fholgado/minibufexpl.vim'

Bundle 'wincent/Command-T'

Bundle 'taglist.vim'

" Bundle 'rstacruz/sparkup', {'rtp': 'vim/'}
" Bundle 'tpope/vim-rails.git'
" vim-scripts repos
" Bundle 'L9'
" Bundle 'FuzzyFinder'
" non-GitHub repos
" Bundle 'git://git.wincent.com/command-t.git'
" Git repos on your local machine (i.e. when working on your own plugin)
" Bundle 'file:///Users/gmarik/path/to/plugin'
" ...

filetype plugin indent on     " required!
"
" Brief help
" :BundleList          - list configured bundles
" :BundleInstall(!)    - install (update) bundles
" :BundleSearch(!) foo - search (or refresh cache first) for foo
" :BundleClean(!)      - confirm (or auto-approve) removal of unused bundles
"
" see :h vundle for more details or wiki for FAQ
" NOTE: comments after Bundle commands are not allowed.


" Map Ctrl+<movement> to move around windows.
map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-l> <c-w>l
map <c-h> <c-w>h

set incsearch

" Remove trailing whitespace
autocmd BufWritePre * :%s/\s\+$//e

" Powerline setup
set term=xterm-256color
set guifont=Menlo\ for\ Powerline\ 9
set laststatus=2

" NERD Tree setup
" F2 to toggle the tree view
map <F2> :NERDTreeToggle<CR>
let NERDTreeIgnore=['\~$', '\.pyc$']

" Python mode setup
let g:pymode_lint_ignore = "E501"
let g:pymode_lint_select = ""
let g:pymode_folding = 0

set wildignore+=*.o,*.pyc

" Taglist setup
map <F3> :TlistToggle<CR>
let Tlist_Exit_OnlyWindow = 1
let Tlist_Show_One_File = 1
let Tlist_Inc_Winwidth = 0
let Tlist_Enable_Fold_Column = 0
let Tlist_GainFocus_On_ToggleOpen = 1
let Tlist_Show_Menu = 0
